version: "3"
services: 
    app:
        container_name: youtube_flask
        build: 
            context: ../
            dockerfile: deployments/app/Dockerfile
        ports: 
            - "5000:5000"